## Deliverable 2. Create a Customer Travel Destinations Map.

In [4]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [5]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head(10)

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Barrow,US,71.2906,-156.7887,-16.99,78,0,8.23,clear sky
1,1,Kulhudhuffushi,MV,6.6221,73.0700,29.36,69,11,2.76,few clouds
2,2,Carutapera,BR,-1.1950,-46.0200,24.67,92,100,2.89,light rain
3,3,Dikson,RU,73.5069,80.5464,-2.24,84,100,9.46,overcast clouds
4,4,Bambous Virieux,MU,-20.3428,57.7575,28.45,69,40,7.72,scattered clouds
5,5,Albany,US,42.6001,-73.9662,7.90,86,90,1.30,overcast clouds
6,6,At-Bashi,KG,41.1702,75.8106,12.15,46,9,1.16,clear sky
7,7,Atuona,PF,-9.8000,-139.0333,26.10,75,14,6.79,few clouds
8,8,Butaritari,KI,3.0707,172.7902,27.70,69,100,1.67,overcast clouds
9,9,Sitka,US,57.0531,-135.3300,2.94,48,0,2.06,clear sky

In [6]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 10
What is the maximum temperature you would like for your trip? 13

In [7]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_city_df = city_data_df.loc[(city_data_df["Max Temp"]<= max_temp) & (city_data_df["Max Temp"]>= min_temp)]
preferred_city_df

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
6,6,At-Bashi,KG,41.1702,75.8106,12.15,46,9,1.16,clear sky
14,14,Rocha,UY,-34.4833,-54.3333,12.85,74,94,1.31,overcast clouds
16,16,Hasaki,JP,35.7333,140.8333,11.22,88,100,11.84,light rain
18,18,Muros,ES,42.7762,-9.0603,10.09,90,0,2.66,clear sky
22,22,Mataura,NZ,-46.1927,168.8643,11.67,74,10,0.98,clear sky
39,39,Balclutha,NZ,-46.2339,169.7500,11.28,67,6,1.14,clear sky
53,53,Constitucion,CL,-35.3333,-72.4167,11.50,92,64,1.51,broken clouds
57,57,Castro,BR,-24.7911,-50.0119,11.50,85,100,2.81,overcast clouds
79,79,Mar Del Plata,AR,-38.0023,-57.5575,11.60,84,0,2.24,clear sky
98,98,Hermanus,ZA,-34.4187,19.2345,11.56,62,95,8.53,overcast clouds
101,101,Northam,GB,51.0333,-4.2167,10.90,95,12,3.77,few clouds
107,107,Springbok,ZA,-29.6643,17.8865,10.65,54,0,1.77,clear sky
122,122,Lasa,IT,46.6166,10.7002,11.72,93,98,1.92,overcast clouds
126,126,Lebu,CL,-37.6167,-73.6500,11.14,88,85,4.17,overcast clouds
127,127,Kuminskiy,RU,58.6667,66.5667,12.76,91,100,3.63,overcast clouds
161,161,Neosho,US,36.8690,-94.3680,12.23,43,100,2.24,overcast clouds
182,182,Bethel,US,41.3712,-73.4140,12.74,53,100,3.58,overcast clouds
185,185,Reconquista,AR,-29.1500,-59.6500,10.12,76,0,1.58,clear sky
209,209,Izberbash,RU,42.5696,47.8645,11.03,67,7,3.51,clear sky
217,217,Lata,PT,40.1629,-8.3327,11.61,84,0,1.17,clear sky
218,218,Oban,GB,56.4127,-5.4706,10.21,87,100,2.47,overcast clouds
257,257,Kaitangata,NZ,-46.2817,169.8464,12.52,69,8,2.16,clear sky
267,267,Tuatapere,NZ,-46.1333,167.6833,12.97,80,91,2.13,overcast clouds
277,277,Nospelt,LU,49.6753,6.0089,12.23,89,0,4.12,clear sky
292,292,Tateyama,JP,34.9833,139.8667,12.96,88,75,4.12,mist
302,302,Kyra,RU,49.5776,111.9753,10.26,24,21,10.26,few clouds
309,309,Lompoc,US,34.6391,-120.4579,11.43,87,40,10.73,mist
314,314,Bantry,IE,51.6833,-9.4500,10.99,94,100,3.28,overcast clouds
322,322,Margate,GB,51.3813,1.3862,12.15,92,100,0.45,overcast clouds
335,335,Viedma,AR,-40.8135,-62.9967,12.85,64,0,5.88,clear sky
343,343,Fort-Shevchenko,KZ,44.5086,50.2630,11.65,58,2,4.22,clear sky
345,345,Whittlesea,ZA,-32.1759,26.8244,12.52,87,100,4.30,overcast clouds
355,355,Ganzhou,CN,28.8184,115.4327,12.34,88,100,4.65,moderate rain
362,362,Vallenar,CL,-28.5708,-70.7581,11.84,85,0,0.40,clear sky
384,384,Rio Gallegos,AR,-51.6226,-69.2181,11.98,71,91,0.43,overcast clouds
391,391,Xining,CN,36.6167,101.7667,12.10,40,100,3.14,overcast clouds
392,392,Lamar,US,33.6668,-95.5836,12.58,68,3,4.01,clear sky
407,407,Hirado,JP,33.3597,129.5531,12.99,77,100,13.60,overcast clouds
419,419,Zhaotong,CN,27.3167,103.7167,11.81,88,100,3.62,overcast clouds
425,425,Melfi,IT,40.9965,15.6514,10.78,64,100,0.50,overcast clouds
428,428,Nizhnevartovsk,RU,60.9344,76.5531,11.01,50,0,3.00,clear sky
434,434,Namyslow,PL,51.0759,17.7228,10.74,85,96,4.23,overcast clouds
458,458,Te Anau,NZ,-45.4167,167.7167,11.61,84,30,2.49,scattered clouds
481,481,Bridlington,GB,54.0831,-0.1919,11.12,93,97,3.71,overcast clouds
482,482,Bartlesville,US,36.7473,-95.9808,12.84,50,100,1.34,overcast clouds
484,484,Berezovka,BY,53.7214,25.4993,10.40,73,100,2.24,overcast clouds
495,495,Boone,US,39.0334,-92.3335,10.44,68,2,4.89,clear sky
544,544,Areosa,PT,41.7178,-8.8571,12.78,78,1,1.56,clear sky
555,555,Romny,UA,50.7510,33.4747,10.43,56,78,1.74,broken clouds
558,558,Nombre De Dios,MX,23.8500,-104.2333,12.85,28,93,1.68,overcast clouds
560,560,Karakol,KG,42.4907,78.3936,12.23,55,5,1.67,clear sky
566,566,Shitanjing,CN,39.2342,106.3439,11.87,41,66,11.60,broken clouds
582,582,Selenduma,RU,50.9131,106.2406,12.77,17,22,1.21,few clouds
594,594,Starokostyantyniv,UA,49.7576,27.2034,12.81,49,99,4.81,overcast clouds
597,597,Mragowo,PL,53.8644,21.3051,10.00,89,100,3.82,overcast clouds
609,609,Warwick,US,41.7001,-71.4162,10.40,89,100,2.57,overcast clouds
649,649,Oxford,GB,51.7522,-1.2560,10.13,98,100,1.03,overcast clouds
663,663,Olkhovka,RU,53.2115,60.6069,11.84,61,100,5.89,overcast clouds
664,664,Palmer,US,42.1584,-72.3287,11.80,63,0,2.06,clear sky

In [8]:
# 4a. Determine if there are any empty rows.
preferred_city_df.count()

Unnamed: 0             59
City                   59
Country                59
Lat                    59
Lng                    59
Max Temp               59
Humidity               59
Cloudiness             59
Wind Speed             59
Current Description    59
dtype: int64

In [9]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [10]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_city_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,At-Bashi,KG,12.15,clear sky,41.1702,75.8106,
14,Rocha,UY,12.85,overcast clouds,-34.4833,-54.3333,
16,Hasaki,JP,11.22,light rain,35.7333,140.8333,
18,Muros,ES,10.09,clear sky,42.7762,-9.0603,
22,Mataura,NZ,11.67,clear sky,-46.1927,168.8643,
39,Balclutha,NZ,11.28,clear sky,-46.2339,169.7500,
53,Constitucion,CL,11.50,broken clouds,-35.3333,-72.4167,
57,Castro,BR,11.50,overcast clouds,-24.7911,-50.0119,
79,Mar Del Plata,AR,11.60,clear sky,-38.0023,-57.5575,
98,Hermanus,ZA,11.56,overcast clouds,-34.4187,19.2345,

In [15]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print(f"index {index} : Hotel not found near {row['City']}, {row['Country']}... skipping.")

index 127 : Hotel not found near Kuminskiy, RU... skipping.
index 302 : Hotel not found near Kyra, RU... skipping.
index 582 : Hotel not found near Selenduma, RU... skipping.
index 663 : Hotel not found near Olkhovka, RU... skipping.

In [17]:
# 7. Drop the rows where there is no Hotel Name.

clean_hotel_df = hotel_df.loc[(hotel_df["Hotel Name"]!="")]
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
6,At-Bashi,KG,12.15,clear sky,41.1702,75.8106,Hostel At-Bashy
14,Rocha,UY,12.85,overcast clouds,-34.4833,-54.3333,Hotel Arrarte
16,Hasaki,JP,11.22,light rain,35.7333,140.8333,Inubosaki Kanko Hotel
18,Muros,ES,10.09,clear sky,42.7762,-9.0603,Apartment Av. Castelao
22,Mataura,NZ,11.67,clear sky,-46.1927,168.8643,Ellie's Villa
39,Balclutha,NZ,11.28,clear sky,-46.2339,169.7500,Hotel South Otago
53,Constitucion,CL,11.50,broken clouds,-35.3333,-72.4167,Hotel Boutique Las Azucenas
57,Castro,BR,11.50,overcast clouds,-24.7911,-50.0119,CHACARA BAILLY
79,Mar Del Plata,AR,11.60,clear sky,-38.0023,-57.5575,Gran Hotel Mar del Plata
98,Hermanus,ZA,11.56,overcast clouds,-34.4187,19.2345,Misty Waves Boutique Hotel
101,Northam,GB,10.90,few clouds,51.0333,-4.2167,Durrant House Hotel
107,Springbok,ZA,10.65,clear sky,-29.6643,17.8865,Undulata Country Lodge
122,Lasa,IT,11.72,overcast clouds,46.6166,10.7002,Pension Feldgärtenhof
126,Lebu,CL,11.14,overcast clouds,-37.6167,-73.6500,Hostal Las Lilas
161,Neosho,US,12.23,overcast clouds,36.8690,-94.3680,Best Western Big Spring Lodge
182,Bethel,US,12.74,overcast clouds,41.3712,-73.4140,Courtyard by Marriott Danbury
185,Reconquista,AR,10.12,clear sky,-29.1500,-59.6500,Grand Hotel
209,Izberbash,RU,11.03,clear sky,42.5696,47.8645,Ramina
217,Lata,PT,11.61,clear sky,40.1629,-8.3327,Casa Maquia
218,Oban,GB,10.21,overcast clouds,56.4127,-5.4706,Muthu Oban Hotel (Formerly Regent Hotel)
257,Kaitangata,NZ,12.52,clear sky,-46.2817,169.8464,Kaitangata Motor Camp
267,Tuatapere,NZ,12.97,overcast clouds,-46.1333,167.6833,Ron and Tony's Bed & Breakfast
277,Nospelt,LU,12.23,clear sky,49.6753,6.0089,Hotel L'Empire
292,Tateyama,JP,12.96,mist,34.9833,139.8667,Tateyama Seaside Hotel
309,Lompoc,US,11.43,mist,34.6391,-120.4579,"Holiday Inn Express Lompoc, an IHG Hotel"
314,Bantry,IE,10.99,overcast clouds,51.6833,-9.4500,The Maritime Hotel
322,Margate,GB,12.15,overcast clouds,51.3813,1.3862,Premier Inn Margate hotel
335,Viedma,AR,12.85,clear sky,-40.8135,-62.9967,Hotel Cristal
343,Fort-Shevchenko,KZ,11.65,clear sky,44.5086,50.2630,Oasis hotel Bautino
345,Whittlesea,ZA,12.52,overcast clouds,-32.1759,26.8244,Eddie's Nest B&B
355,Ganzhou,CN,12.34,moderate rain,28.8184,115.4327,Zhanqian Grand Hotel
362,Vallenar,CL,11.84,clear sky,-28.5708,-70.7581,Humacao Bed & Breakfast
384,Rio Gallegos,AR,11.98,overcast clouds,-51.6226,-69.2181,Hotel Santa Cruz
391,Xining,CN,12.10,overcast clouds,36.6167,101.7667,Super Leisure Hotel
392,Lamar,US,12.58,clear sky,33.6668,-95.5836,Kings Inn Paris TX
407,Hirado,JP,12.99,overcast clouds,33.3597,129.5531,Samson Hotel
419,Zhaotong,CN,11.81,overcast clouds,27.3167,103.7167,Jingguan Home
425,Melfi,IT,10.78,overcast clouds,40.9965,15.6514,HOTEL TERME DI RAPOLLA
428,Nizhnevartovsk,RU,11.01,clear sky,60.9344,76.5531,Luch
434,Namyslow,PL,10.74,overcast clouds,51.0759,17.7228,Hotel Zorza
458,Te Anau,NZ,11.61,scattered clouds,-45.4167,167.7167,Kingsgate Hotel Te Anau
481,Bridlington,GB,11.12,overcast clouds,54.0831,-0.1919,Expanse Bridlington Seafront Hotel
482,Bartlesville,US,12.84,overcast clouds,36.7473,-95.9808,Hilton Garden Inn Bartlesville
484,Berezovka,BY,10.40,overcast clouds,53.7214,25.4993,Nad Nemanom Usad'ba
495,Boone,US,10.44,clear sky,39.0334,-92.3335,Cottonwoods RV Park
544,Areosa,PT,12.78,clear sky,41.7178,-8.8571,Hotel Flôr de Sal
555,Romny,UA,10.43,broken clouds,50.7510,33.4747,Floriana
558,Nombre De Dios,MX,12.85,overcast clouds,23.8500,-104.2333,Uraján de Luna Hotel Boutique & SPA
560,Karakol,KG,12.23,clear sky,42.4907,78.3936,"Gostinitsa ""Al'tamira"""
566,Shitanjing,CN,11.87,broken clouds,39.2342,106.3439,Yingbin Hotel
594,Starokostyantyniv,UA,12.81,overcast clouds,49.7576,27.2034,Lider
597,Mragowo,PL,10.00,overcast clouds,53.8644,21.3051,Hotel Anek
609,Warwick,US,10.40,overcast clouds,41.7001,-71.4162,Hampton Inn & Suites Providence/Warwick-Airport
649,Oxford,GB,10.13,overcast clouds,51.7522,-1.2560,Malmaison Oxford
664,Palmer,US,11.80,clear sky,42.1584,-72.3287,Wedgewood Motel

In [18]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="ID")

In [19]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °C</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [24]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(17.0, 40.0), zoom_level=1.7)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))